name: Automate Briq & Vanir CSV Fetch & Upload

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 5 AM NYC time (9 AM UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🛠 Install Dependencies
        run: npm install puppeteer

      - name: 🌍 Install Chrome for Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          if [ ! -f /usr/bin/google-chrome ]; then
            ln -s /usr/bin/google-chrome-stable /usr/bin/google-chrome
          fi
          echo "✅ Chrome Installed"



      - name: 🚀 Run Puppeteer Script (Briq & Vanir)
        env:
          BRIQ_USERNAME: ${{ secrets.BRIQ_USERNAME }}
          BRIQ_PASSWORD: ${{ secrets.BRIQ_PASSWORD }}
          VANIR_USERNAME: ${{ secrets.VANIR_USERNAME }}
          VANIR_PASSWORD: ${{ secrets.VANIR_PASSWORD }}
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome"
        run: downloadsalescsv.js

      - name: 🔄 Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "richard.mcgirt@vanirinstalledsales.com"
          git config --global user.name "RichardMcGirt"
          git remote set-url origin https://github.com/RichardMcGirt/Briqdata.git
          git pull origin main
          git add .
          git commit -m "Automated upload of latest sales CSV" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/RichardMcGirt/Briqdata.git main || echo "No changes to push"
