name: Automate CSV Fetch & Upload

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VANIR_USERNAME: ${{ secrets.VANIR_USERNAME }}
          VANIR_PASSWORD: ${{ secrets.VANIR_PASSWORD }}
        run: node run_daily_tasks.js
