name: Download and Upload CSV

on:
  schedule:
    - cron: "0 10 * * *"  # Runs daily at 6 AM Eastern Time
  workflow_dispatch:  # Allows manual execution

jobs:
  run-puppeteer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Puppeteer Dependencies
        run: |
          sudo apt-get install -y \
            libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 \
            libxcomposite1 libxrandr2 libxdamage1 libxkbcommon0 libpango-1.0-0 libgtk-3-0 \
            libasound2t64
          npm install

      - name: Install Puppeteer Chrome
        run: npx puppeteer browsers install chrome

      - name: Create Downloads Directory
        run: mkdir -p ~/work/Briqdata/Briqdata/downloads  # ✅ Ensure directory exists

      - name: Run Puppeteer Script to Download CSV
        run: node run_daily_tasks.js || (echo "❌ Puppeteer script failed!" && exit 1)

      - name: Debug: List Downloaded Files  # ✅ FIXED INDENTATION
        run: ls -l ~/work/Briqdata/Briqdata/downloads  # ✅ Show files downloaded

      - name: Check if CSV File Exists
        run: |
          CSV_DIR=~/work/Briqdata/Briqdata/downloads  # ✅ Corrected path
          CSV_FILE=$(ls $CSV_DIR | grep "richard_mcgirt_vanirinstalledsales_com" | tail -n 1)
          if [[ -z "$CSV_FILE" ]]; then
            echo "❌ No CSV file found in $CSV_DIR. Exiting."
            exit 1
          else
            echo "✅ CSV file found: $CSV_FILE"
          fi
        shell: bash

      - name: Move CSV File to Repository
        run: |
          CSV_DIR=~/work/Briqdata/Briqdata/downloads
          CSV_FILE=$(ls $CSV_DIR | grep "richard_mcgirt_vanirinstalledsales_com" | tail -n 1)
          mv "$CSV_DIR/$CSV_FILE" ./
          echo "✅ Moved $CSV_FILE to repo"
        shell: bash

      - name: Configure Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "GitHub Action Bot"

      - name: Commit and Push CSV
        run: |
          git add .
          git commit -m "Automated upload: $(date +'%Y-%m-%d')"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/RichardMCGirt/Briqdata.git main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
