name: Upload CSV to GitHub

on:
   schedule:
    - cron: "0 10 * * *"  # Runs daily at 6 AM Eastern Time (adjusted for UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Run Script
        run: |
          node downloadsalescsv.js

      - name: Commit and Push CSV
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Action Bot"
          git add .
          git commit -m "Automated CSV Upload" || echo "No changes to commit"
          git push
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
